/* Copyright 2011 Eumetsat */
package eu.eumetsat.skat.utils;

/** Input parameter keys for SKAT.
 */
public enum ParameterKey {

    OUTPUT_FILE_NAME,

    INERTIAL_FRAME,
    EARTH_FRAME,
    GRAVITY_FIELD_DEGREE,
    GRAVITY_FIELD_ORDER,

    ORBIT_CARTESIAN_DATE,
    ORBIT_CARTESIAN_POSITION,
    ORBIT_CARTESIAN_VELOCITY,

    ORBIT_KEPLERIAN_DATE,
    ORBIT_KEPLERIAN_A,
    ORBIT_KEPLERIAN_E,
    ORBIT_KEPLERIAN_I,
    ORBIT_KEPLERIAN_PA,
    ORBIT_KEPLERIAN_RAAN,
    ORBIT_KEPLERIAN_MEAN_ANOMALY,

    ORBIT_CIRCULAR_DATE,
    ORBIT_CIRCULAR_A,
    ORBIT_CIRCULAR_EX,
    ORBIT_CIRCULAR_EY,
    ORBIT_CIRCULAR_I,
    ORBIT_CIRCULAR_RAAN,
    ORBIT_CIRCULAR_MEAN_LATITUDE_ARGUMENT,

    ORBIT_EQUINOCTIAL_DATE,
    ORBIT_EQUINOCTIAL_A,
    ORBIT_EQUINOCTIAL_EX,
    ORBIT_EQUINOCTIAL_EY,
    ORBIT_EQUINOCTIAL_HX,
    ORBIT_EQUINOCTIAL_HY,
    ORBIT_EQUINOCTIAL_MEAN_LONGITUDE_ARGUMENT,

    SIMULATION_START_DATE,
    SIMULATION_POSITION_TOLERANCE,
    SIMULATION_CYCLE_DURATION,
    SIMULATION_CYCLE_NUMBER;

}
