/* Copyright 2011 Eumetsat */
package eu.eumetsat.skat.utils;

/** Input parameter keys for SKAT.
 */
public enum ParameterKey {

    OUTPUT_FILE_NAME,

    INERTIAL_FRAME,
    EARTH_FRAME,
    GRAVITY_FIELD_DEGREE,
    GRAVITY_FIELD_ORDER,

    ORBIT_CIRCULAR_DATE,
    ORBIT_CIRCULAR_A,
    ORBIT_CIRCULAR_EX,
    ORBIT_CIRCULAR_EY,
    ORBIT_CIRCULAR_I,
    ORBIT_CIRCULAR_RAAN,
    ORBIT_CIRCULAR_ALPHA,

    ORBIT_EQUINOCTIAL_DATE,
    ORBIT_EQUINOCTIAL_A,
    ORBIT_EQUINOCTIAL_EX,
    ORBIT_EQUINOCTIAL_EY,
    ORBIT_EQUINOCTIAL_HX,
    ORBIT_EQUINOCTIAL_HY,
    ORBIT_EQUINOCTIAL_LAMBDA,

    SIMULATION_START_DATE,
    SIMULATION_CYCLE_DURATION,
    SIMULATION_CYCLE_NUMBER;

}
